import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const loginWithMetamask = async () => {
    console.log('loginWithMetamask');
    
    // Check if metamask is installed
    if (typeof window.ethereum !== 'undefined') {
      console.log('MetaMask is installed!');
  
      // Get the metamask account
      const accounts = await ethereum.request({ method: 'eth_requestAccounts' });

      // Get the user account
      const account = accounts[0];

      console.log(account);
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            
              
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />


            <button onClick={loginWithMetamask}>
              Click Me
            </button>
            
          </div>
        </div>

        <div className={styles.center}>
          
        </div>

        <div className={styles.grid}>
          
        </div>
      </main>
    </>
  )
}
