import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Icon, TextField } from '@taikai/rocket-kit'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>  
          {/* <HorizontalNav
            items={[
              <li key="0" className="active"><a href="#0"><Icon icon="overview" />Create Event</a></li>,
              <li key="1"><a href="#0"><Icon icon="timeline" />Events</a></li>,
              <li key="2"><a href="#0"><Icon icon="rules" />History</a></li>,
              <li key="3"><a href="#0"><Icon icon="resources" />Profile</a></li>
            ]}
          /> */}
        </div>

        <div className={styles.center}>

          <TextField
            name="awesome-input"
            // onChange={function noRefCheck(){}}
            placeholder="Awesome Placeholder"
            type="text"
          />

        </div>



      </main>
    </>
  )
}
